# Numpy tutorials
Numpy is a general-purpose array-processing package. It provides a high- performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python.

# What is an array
An array is a data structure that stores values of same data type. In python, this is the main differeence between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

In [8]:
# Put this command in cmd to install numpy
#pip install numpy
# conda install numpy - to install numpy in anaconda

In [1]:
# Importing a numpy 
import numpy as np

In [3]:
my_list=[2,3,4,5,6,1]
arr=np.array(my_list)

In [4]:
my_list

[2, 3, 4, 5, 6, 1]

In [5]:
arr

array([2, 3, 4, 5, 6, 1])

In [6]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(6,)

In [10]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[3,4,5,6,7]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [11]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [12]:
arr.shape

(3, 5)

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

# Indexing

In [45]:
# Accessing the array elements
arr=np.array([1,2,3,4,5,6,7])

In [46]:
arr[3]

4

In [20]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[3,4,5,6,7]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [21]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [22]:
arr[1:,3:]

array([[5, 6],
       [6, 7]])

In [23]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [24]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [26]:
arr[0:2,2:4]

array([[3, 4],
       [4, 5]])

In [33]:
arr[1:,4:]

array([[6],
       [7]])

In [35]:
arr[1:,2:4]

array([[4, 5],
       [5, 6]])

In [36]:
arr[1:,1:3]

array([[3, 4],
       [4, 5]])

In [37]:
arr=np.arange(0,10)

In [43]:
arr

array([0, 2, 4, 6, 8])

In [39]:
arr=np.arange(0,10,step=2)

In [47]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
##copy() function and broadcasting 
arr[3:]=100

In [51]:
arr

array([  1,   2,   3, 100, 100, 100, 100])

In [42]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [52]:
arr1=arr.copy()

In [53]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 100 100 100 100]
[   1    2    3 1000 1000 1000 1000]


In [55]:
## Some conditions very useful in exploratory data analysis
val=4
arr[arr<val]

array([1, 2, 3])

In [56]:
## Create array and reshape it.
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [57]:
arr1=np.arange(0,10).reshape(5,2)

In [58]:
arr2=np.arange(0,10).reshape(5,2)

In [61]:
arr=arr1*arr2

In [62]:
arr

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [63]:
arr/2

array([[ 0. ,  0.5],
       [ 2. ,  4.5],
       [ 8. , 12.5],
       [18. , 24.5],
       [32. , 40.5]])

In [64]:
np.ones(4)

array([1., 1., 1., 1.])

In [70]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [76]:
#random distribution
np.random.rand(3,3)

array([[0.0511298 , 0.63031879, 0.87774568],
       [0.46145966, 0.33639555, 0.36135112],
       [0.82670775, 0.76639006, 0.65051269]])

In [77]:
arr_ex=np.random.randn(4,4)

In [78]:
arr_ex

array([[-0.06287574, -0.82587842,  1.10814707, -0.20867312],
       [-0.0859199 , -0.32788712, -0.89301178,  2.31110319],
       [ 1.55433174, -0.37082118,  0.69548361,  0.29377834],
       [-0.14840236,  1.49418547,  0.91477134, -0.84956132]])